import { v2 as cloudinary } from "cloudinary";
import { CloudinaryStorage } from "multer-storage-cloudinary";
import multer from "multer";
import dotenv from "dotenv";
import path from "path";

// Load env vars if they aren't loaded yet
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

// Configure Cloudinary
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

// Setup Multer Storage using Cloudinary
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: async (req, file) => {
    // Generate a unique folder or use a default one based on route
    const folder = req.baseUrl.includes("admin") ? "rentalsphere/vehicles" : "rentalsphere/users";

    // Set allowed formats
    const allowedFormats = ["jpeg", "png", "jpg", "webp"];

    return {
      folder: folder,
      allowed_formats: allowedFormats,
      // unique filename generated by cloudinary automatically
    };
  },
});

// Create Multer instance
export const upload = multer({
  storage: storage,
  limits: {
    fileSize: 5 * 1024 * 1024, // 5MB limit
  },
  fileFilter: (req, file, cb) => {
    // 1. Sanitize original filename (prevent Directory Traversal / Null Byte Injection)
    // path.basename strips out any directory paths like ../../../
    // .replace(/\0/g, '') removes null bytes
    const sanitizedFilename = path.basename(file.originalname).replace(/\0/g, "");
    // 2. Prevent Double Extensions (e.g. shell.php.png)
    // To strictly prevent execution bypasses on misconfigured web servers, reject any filename with multiple dots.
    if (sanitizedFilename.split(".").length > 2) {
      return cb(new Error(`File upload rejected: Filenames with multiple dots/extensions are not allowed.`));
    }

    // 3. Extract and validate extension (prevent RCE)
    const ext = path.extname(sanitizedFilename).toLowerCase();
    const ALLOWED_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp"];
    if (!ALLOWED_EXTENSIONS.includes(ext)) {
      return cb(new Error(`File upload rejected: Extension ${ext} is not allowed.`));
    }

    // 3. Validate MIME type (prevent RCE)
    const ALLOWED_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"];
    if (!ALLOWED_MIME_TYPES.includes(file.mimetype)) {
      return cb(new Error(`File upload rejected: MIME type ${file.mimetype} is not allowed.`));
    }

    // Overwrite original name with sanitized version to prevent traversal later down the line
    file.originalname = sanitizedFilename;

    // Passed all security checks
    cb(null, true);
  },
});